facil = [
    ("Blanco por dentro, amarillo por fuera. Si quieres que te lo diga, espera.", "Limon"),
    ("Todos me pisan, pero yo nunca me enojo. ¿Qué soy?", "Piso"),
    ("Tiene agujas pero no cose; da la hora sin hablar.", "Reloj"),
    ("En el agua nací, en el agua me crié; si no me mojas, me moriré.", "Pez"),
    ("Vivo en el campo o en la ciudad, doy luz de noche y brillo sin parar.", "Farol"),
    ("Siempre va delante y nunca se cansa; si llueve lo usas, si no, no lo usas.", "Paraguas"),
    ("Cae sin hacer ruido, no es lluvia ni es cabello; cubre montes y valles con un manto blanco.", "Nieve"),
    ("Tiene muchas teclas pero no abre puertas; toca musica si lo presionas.", "Piano"),
    ("Me buscas cuando hace frio, me quitas cuando hace calor; me pones y me quitas sin pensar.", "Ropa"),
    ("En el campo me encienden, en la cocina me apagan; con fuego me hacen y sin fuego me apago.", "Vela"),
    ("Me cebas por la mañana, me compartis con amigos; hago burbujas en la bombilla y soy infaltable en el mate.", "Mate"),
    ("Paso por la ciudad, subis y bajas; tengo paradas y asiento pero no soy un tren.", "Colectivo"),
    ("Me prendes para el frio, me usas en la parrilla y soy excusa perfecta para juntarse a comer.", "Asado"),
    ("Tengo filas y andenes, debajo de la ciudad voy y vengo; en Buenos Aires a mucha gente le ahorro el transito.", "Subte"),
    ("Soy dulce y cremoso, me untas en la tostada o en la medialuna; naci para alegrar el desayuno.", "Dulce de leche"),
    ("Me ponen en la bandera, brillo en el escudo y a veces me nombran en canciones patrias.", "Sol"),
    ("Tengo agujeros por todos lados, pero igualmente guardo agua.", "Esponja"),
    ("Soy redondo, ruedo por la calle y te llevo si me subis; tengo volante y puertas pero no soy casa.", "Auto"),
    ("Sale de noche y a veces se ve llena; ilumina el cielo y cambia de cara.", "Luna"),
    ("Brilla sin ser lampara, calienta sin ser fuego; cuando aparece es de dia, cuando se esconde llega el sueño.", "Sol"),
]

medio = [
    ("Siempre llega pero nunca esta; si lo buscas, ya paso.", "Futuro"),
    ("Me puedes abrir y tambien cerrar, guardo secretos y a veces lloro tinta.", "Carta"),
    ("Nace del frio y del calor muere; a veces es arte, a veces es ciencia; lo ves en la calle y en el vaso.", "Hielo"),
    ("Me usan los sabios para escribir, los tontos para borrar; en secreto guardo la primera idea.", "Lapiz"),
    ("Va y viene sin moverse, lleva nombres y pueblos, pero nunca sale del papel.", "Mapa"),
    ("Tiene hojas sin ser arbol, cubre el mundo sin ser manta; quien me lee viaja sin moverse.", "Libro"),
    ("Me inventaron para contar, me rompen para sumar; tengo caras y a veces valor.", "Moneda"),
    ("Puedes verme pero no tocarme; reflejo lo que hay, aunque no tenga existencia propia.", "Espejo"),
    ("Si me nombras desaparezco; soy presencia que no hace ruido.", "Silencio"),
    ("Voy de casa en casa, me abres con toque y guardo lo que pides; a veces cerrada, a veces abierta.", "Puerta"),
    ("Soy amigo de la siembra, traigo colores y aromas; la cortan para hacer arreglos.", "Flor"),
    ("Me lanzas al aire para que vuelva; si me olvidas en casa, el juego se termina.", "Pelota"),
    ("Tengo dientes que no muerden, tengo boca que no habla; en la cocina me mandan y en la mesa me respetan.", "Tenedor"),
    ("No ves mi cuerpo pero sientes mi fuerza; me usan para mover barcos, moler granos y encender cometas.", "Viento"),
    ("Soy firme como roca pero con tiempo me desgasto; la naturaleza me esculpe y el agua me besa.", "Montana"),
    ("No soy persona pero tengo edad; cuanto mas me usan, menos me queda.", "Bateria"),
    ("Soy hierba y aroma, me mezclan con aji, aceite y perejil; no falto en la parrilla ni en la mesa.", "Chimichurri"),
    ("Naci de la tierra, me moldean las manos; me vuelvo casa, vasija o estatua cuando me secan y me cuecen.", "Arcilla"),
    ("Me ponen en la calle para que andes seguro; si no me respetas, el viaje se complica.", "Semaforo"),
    ("Naci para medir, tiendo a marcar limites; a veces flexible, otras rigida.", "Regla"),
]

dificil = [
    ("Me alimentan pero no me ves crecer; si me das demasiada luz, desaparezco.", "Sombra"),
    ("Me encuentras en la cima y en el abismo; soy causa de guerra y promesa de paz; me trazan con tinta y con sangre.", "Frontera"),
    ("Naci como numero, me usan para medir la vida; si me cortas, cuentas no volveran.", "Edad"),
    ("Soy puente entre preguntas y certezas; me forman hombres y mujeres, pero no soy persona.", "Ciencia"),
    ("Me buscas en el final de un cuento y en la firma de un trato; sin mi todo queda abierto.", "Firma"),
    ("Me buscas cuando no me tienes y me pierdes cuando me presumes.", "Humildad"),
    ("Naci del agua y del sol, me rompo con la sombra y me sostengo en el aire.", "Arcoiris"),
    ("Me guardan los sabios y me pierden los imprudentes; soy llave para puertas del saber.", "Experiencia"),
    ("Estoy en la punta de la lengua y no siempre hablo; cuanto mas me callas, mas te cuestionan.", "Duda"),
    ("No tengo cuerpo pero puedo influir en multitudes; con palabras me encienden o me apagan.", "Ideologia"),
    ("Me usan para ver lo pequeno y para encontrar lo oculto; amplio pero tambien engano.", "Lupa"),
    ("Me afinan para cantar y me golpean para contar; marco ritmo y acompano mitos.", "Tambor"),
    ("Soy recuerdo que no envejece; me guardan en cajas y albumes.", "Foto"),
    ("Me inventaron para proteger y ahora me usan para espiar; cambio segun quien me tenga.", "Contrasena"),
    ("Soy companero del cientifico y enemigo del fraude; me exigen en la investigacion y en el juicio.", "Evidencia"),
    ("Me escriben para ordenar y me rompen para escapar; sin mi las ciudades serian caos.", "Ley"),
    ("No camino pero recorro continentes; no respiro pero cambio climas; me pintan en mapas.", "Oceano"),
    ("Traigo ritmo sin corazon; me marcan los pies y me interpretan las manos.", "Musica"),
    ("Soy espejo de epocas; me guardan en museos y me ayudan a entender.", "Arte"),
    ("Me alimentan con datos y me piden explicaciones; sin mi, la decision es a ciegas.", "Estadistica"),
]
